### ISSUE TITLE
Add the ability to maintain additional compose-fragment.yml files for specific purposes

### ISSUE THREAD

**Issue by brooks630** [LandRegistry/common-dev-env#149]
* **I'm submitting a ...**

  * [ ] bug report
  * [x] feature request
  * [ ] support request

* **What is the current behavior?**
The common dev-env is only able to pull in a single `compose-fragment.yml` for each specific respository in the project's dev-env config, resulting in the `compose-fragment.yml` having to define the entire deployment structure of the repo's contents. 

* **What is the expected/proposed behavior?**
It is proposed that the ability to maintain additional `compose-fragment.yml` files for specific purposes be added to the common dev-env. This would be in the following structure:

```
fragments/compose-fragment.yml # default - would not change
fragments/compose-fragment.slim.yml
fragments/compose-fragment.full.yml
```

This would then be referenced in the dev-env config `configuration.yml` in the following manner:

```yaml
applications:
  # default - would not change
  example-repo:
    repo: git@example.com:example/example.git
    branch: master
  # slim
  example-repo:
    repo: git@example.com:example/example.git
    branch: master
    variant: slim
  # full
  example-repo:
    repo: git@example.com:example/example.git
    branch: master
    variant: full
```

* **What is the motivation / use case for changing the behavior?**
The current behaviour is fine for individual microservice repos, however for monolithic repos containing multiple microservices it is not possible to define individual configs for specific purposes (i.e., if only a subset of components in the repo are required). This can be worked around by having separate branches with redefined `compose-fragment.yml` files, however this creates additional complexity in terms of repo management.

* **Please tell us about your environment:**

  * Common-dev-env version: 2.2.0
  * Operating system (and shell, if not the OS default): Fedora (zsh) via WSL2
  * Ruby version: 3.2.2
